In [1]:
import os
import pandas as pd

In [2]:
data=pd.read_csv(r"D:\Full_projects\CustomerChurn\Data\WA_Fn-UseC_-Telco-Customer-Churn.csv")

In [3]:
data.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [4]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   str
 1   gender            7043 non-null   str
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   str
 4   Dependents        7043 non-null   str
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   str
 7   MultipleLines     7043 non-null   str
 8   InternetService   7043 non-null   str
 9   OnlineSecurity    7043 non-null   str
 10  OnlineBackup      7043 non-null   str
 11  DeviceProtection  7043 non-null   str
 12  TechSupport       7043 non-null   str
 13  StreamingTV       7043 non-null   str
 14  StreamingMovies   7043 non-null   str
 15  Contract          7043 non-null   str
 16  PaperlessBilling  7043 non-null   str
 17  PaymentMethod     7043 non-null   str
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   str
 20  Churn             7043 non-null   str
dtypes: float64(1), int64(2), str(18)
memory usage: 1.1 MB

In [5]:
data.describe()

       SeniorCitizen       tenure  MonthlyCharges
count    7043.000000  7043.000000     7043.000000
mean        0.162147    32.371149       64.761692
std         0.368612    24.559481       30.090047
min         0.000000     0.000000       18.250000
25%         0.000000     9.000000       35.500000
50%         0.000000    29.000000       70.350000
75%         0.000000    55.000000       89.850000
max         1.000000    72.000000      118.750000

In [6]:
data.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [7]:
data=data[data["TotalCharges"]!=" "].reset_index()

In [8]:
data["TotalCharges"]=data["TotalCharges"].astype("float32")

In [9]:
data.describe(include="object")

C:\Users\Vivek\AppData\Local\Temp\ipykernel_13772\460854327.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  data.describe(include="object")

,customerID,gender,Partner,Dependents,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,Churn
count,7032,7032,7032,7032,7032,7032,7032,7032,7032,7032,7032,7032,7032,7032,7032,7032,7032
unique,7032,2,2,2,2,3,3,3,3,3,3,3,3,3,2,4,2
top,7590-VHVEG,Male,No,No,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,No
freq,1,3549,3639,4933,6352,3385,3096,3497,3087,3094,3472,2809,2781,3875,4168,2365,5163

In [10]:
for i in data.select_dtypes(include="str"):
    print(f"Unique :,{data[i].unique()},----,{data[i].nunique()}")
    print()
    print("----"*50)

Unique :,<StringArray>
['7590-VHVEG', '5575-GNVDE', '3668-QPYBK', '7795-CFOCW', '9237-HQITU',
 '9305-CDSKC', '1452-KIOVK', '6713-OKOMC', '7892-POOKP', '6388-TABGU',
 ...
 '9767-FFLEM', '0639-TSIQW', '8456-QDAVC', '7750-EYXWZ', '2569-WGERO',
 '6840-RESVB', '2234-XADUH', '4801-JZAZL', '8361-LTMKD', '3186-AJIEK']
Length: 7032, dtype: str,----,7032

--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Unique :,<StringArray>
['Female', 'Male']
Length: 2, dtype: str,----,2

--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Unique :,<StringArray>
['Yes', 'No']
Length: 2, dtype: str,----,2

--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Unique :,<StringArray>
['No', 'Yes']
Length: 2, dtype: str,----,2

--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Unique :,<StringArray>
['No', 'Yes']
Length: 2, dtype: str,----,2

--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Unique :,<StringArray>
['No phone service', 'No', 'Yes']
Length: 3, dtype: str,----,3

--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Unique :,<StringArray>
['DSL', 'Fiber optic', 'No']
Length: 3, dtype: str,----,3

--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Unique :,<StringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str,----,3

--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Unique :,<StringArray>
['Yes', 'No', 'No internet service']
Length: 3, dtype: str,----,3

--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Unique :,<StringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str,----,3

--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Unique :,<StringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str,----,3

--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Unique :,<StringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str,----,3

--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Unique :,<StringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str,----,3

--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Unique :,<StringArray>
['Month-to-month', 'One year', 'Two year']
Length: 3, dtype: str,----,3

--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Unique :,<StringArray>
['Yes', 'No']
Length: 2, dtype: str,----,2

--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Unique :,<StringArray>
[         'Electronic check',              'Mailed check',
 'Bank transfer (automatic)',   'Credit card (automatic)']
Length: 4, dtype: str,----,4

--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Unique :,<StringArray>
['No', 'Yes']
Length: 2, dtype: str,----,2

--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

In [11]:
data.columns

Index(['index', 'customerID', 'gender', 'SeniorCitizen', 'Partner',
       'Dependents', 'tenure', 'PhoneService', 'MultipleLines',
       'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection',
       'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract',
       'PaperlessBilling', 'PaymentMethod', 'MonthlyCharges', 'TotalCharges',
       'Churn'],
      dtype='str')

In [12]:
data.drop(["customerID","index"],inplace=True,axis=1)

In [13]:
data

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.850000,No
1,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.500000,No
2,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.150002,Yes
3,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.750000,No
4,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.649994,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7027,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,No,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.500000,No
7028,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,Yes,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.899902,No
7029,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,No,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.450012,No
7030,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.600006,Yes
7031,Male,0,No,No,66,Yes,No,Fiber optic,Yes,No,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.500000,No

In [14]:
import os

In [15]:
data.to_csv(r"D:\Full_projects\CustomerChurn\Data\cleaned_data.csv", index=False)

In [16]:
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

In [17]:
le=LabelEncoder()
for i in data.select_dtypes(include="object"):
    data[i]=le.fit_transform(data[i])

C:\Users\Vivek\AppData\Local\Temp\ipykernel_13772\718358965.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for i in data.select_dtypes(include="object"):

In [18]:
x=data.drop("Churn",axis=1)
y=data["Churn"]

In [19]:
x.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges
0,0,0,1,0,1,0,1,0,0,2,0,0,0,0,0,1,2,29.85,29.850000
1,1,0,0,0,34,1,0,0,2,0,2,0,0,0,1,0,3,56.95,1889.500000
2,1,0,0,0,2,1,0,0,2,2,0,0,0,0,0,1,3,53.85,108.150002
3,1,0,0,0,45,0,1,0,2,0,2,2,0,0,1,0,0,42.30,1840.750000
4,0,0,0,0,2,1,0,1,0,0,0,0,0,0,0,1,2,70.70,151.649994

In [20]:
y.head()

0    0
1    0
2    1
3    0
4    1
Name: Churn, dtype: int64

In [21]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20,random_state=42)

In [22]:
print("Training Size",x_train.shape,y_train.shape)
print("Testing Size :",x_test.shape,y_test.shape)

Training Size (5625, 19) (5625,)
Testing Size : (1407, 19) (1407,)

In [23]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,classification_report
log=LogisticRegression()
log.fit(x_train,y_train)
y_pred=log.predict(x_test)
print(accuracy_score(y_test,y_pred)*100)

78.53589196872778

d:\ML_Project\env\Lib\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [24]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.83      0.88      0.86      1033
           1       0.61      0.52      0.56       374

    accuracy                           0.79      1407
   macro avg       0.72      0.70      0.71      1407
weighted avg       0.78      0.79      0.78      1407

In [25]:
y_predtrain=log.predict(x_train)
print(accuracy_score(y_train,y_predtrain))

0.8067555555555556

In [26]:
from sklearn.ensemble import RandomForestClassifier
random=RandomForestClassifier()
random.fit(x_train,y_train)
pred=random.predict(x_test)
tpred=random.predict(x_train)
print(accuracy_score(y_train,tpred)*100)
print(accuracy_score(y_test,pred)*100)

99.76888888888888
78.3226723525231

In [30]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import GradientBoostingClassifier,AdaBoostClassifier
from xgboost import XGBClassifier

In [32]:
models={
    "Logistic Regression":LogisticRegression(),
    "Decision Tree Classifier":DecisionTreeClassifier(),
    "Random Forest Classifier":RandomForestClassifier(),
    "Support Vector Machine":SVC(),
    "KNeighbors Classifier":KNeighborsClassifier(),
    "Gradient Boosting Classifier":GradientBoostingClassifier(),
    "AdaBoost Classifier":AdaBoostClassifier(),
    "XGBoost Classifier":XGBClassifier()
}

In [37]:
def model_evaluate(models,x_train,x_test,y_test,y_train):

    for model_name,model in models.items():

        model.fit(x_train,y_train)

        test_pred=model.predict(x_test)
        train_pred=model.predict(x_train)

        train_accuracy=accuracy_score(y_train,train_pred)*100
        test_accuracy=accuracy_score(y_test,test_pred)*100

        print("Model Name :",model_name)
        print("Train Accuracy :",train_accuracy)
        print("Testing Accuracy :",test_accuracy)
        print("---"*50)
        print()

In [38]:
model_evaluate(models,x_train,x_test,y_test,y_train)

d:\ML_Project\env\Lib\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Model Name : Logistic Regression
Train Accuracy : 80.67555555555556
Testing Accuracy : 78.53589196872778
------------------------------------------------------------------------------------------------------------------------------------------------------

Model Name : Decision Tree Classifier
Train Accuracy : 99.76888888888888
Testing Accuracy : 72.636815920398
------------------------------------------------------------------------------------------------------------------------------------------------------

Model Name : Random Forest Classifier
Train Accuracy : 99.76888888888888
Testing Accuracy : 78.3226723525231
------------------------------------------------------------------------------------------------------------------------------------------------------

Model Name : Support Vector Machine
Train Accuracy : 73.42222222222222
Testing Accuracy : 73.41862117981522
------------------------------------------------------------------------------------------------------------------------------------------------------

Model Name : KNeighbors Classifier
Train Accuracy : 83.18222222222222
Testing Accuracy : 77.3276474769012
------------------------------------------------------------------------------------------------------------------------------------------------------

Model Name : Gradient Boosting Classifier
Train Accuracy : 82.80888888888889
Testing Accuracy : 79.60199004975125
------------------------------------------------------------------------------------------------------------------------------------------------------

Model Name : AdaBoost Classifier
Train Accuracy : 80.88888888888889
Testing Accuracy : 78.74911158493248
------------------------------------------------------------------------------------------------------------------------------------------------------

Model Name : XGBoost Classifier
Train Accuracy : 94.75555555555556
Testing Accuracy : 76.97228144989339
------------------------------------------------------------------------------------------------------------------------------------------------------

In [41]:
from sklearn.model_selection import RandomizedSearchCV
model=GradientBoostingClassifier()
param={
    "n_estimators":[100,200,300],
    "learning_rate":[0.01,0.05,0.1],
    "max_depth":[3,5,7],
    "min_samples_split":[2,3,5,6,8],
    "min_samples_leaf":[1,2,4,6,7,9],
    "subsample":[0.8,1.0]
}

random=RandomizedSearchCV(
    model,
    param,
    cv=5,
    scoring="accuracy",
    n_jobs=-1
)


random.fit(x_train,y_train)
print(random.best_estimator_)
print(random.best_score_)
print(random.best_params_)

GradientBoostingClassifier(learning_rate=0.01, max_depth=5, min_samples_leaf=6,
                           min_samples_split=3, n_estimators=200,
                           subsample=0.8)
0.8040888888888889
{'subsample': 0.8, 'n_estimators': 200, 'min_samples_split': 3, 'min_samples_leaf': 6, 'max_depth': 5, 'learning_rate': 0.01}